# Production environment values
replicaCount: 5

image:
  tag: "latest"

env:
  NODE_ENV: "production"
  BASE_URL: "https://your-app.com"
  API_BASE_URL: "https://api.your-app.com"

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

postgresql:
  auth:
    postgresPassword: "production-postgres-secure"
    username: "playwright"
    password: "production-playwright-secure"
    database: "playwright_production"
  primary:
    persistence:
      size: 20Gi

redis:
  master:
    persistence:
      size: 5Gi

testConfig:
  browsers: ["chromium", "firefox", "webkit"]
  parallel: true
  workers: 8
  headless: true
  video: true
  screenshot: true
  trace: true

performance:
  enabled: true
  thresholds:
    lcp: 2000
    fid: 80
    cls: 0.05
    fcp: 1500
    tti: 3000

dataManagement:
  enabled: true
  cleanupStrategy: "auto"
  retention: "7d"
  exportFormats: ["json", "csv", "xml"]
